audio:
  chunk_size: 261120
  dim_f: 4096
  dim_t: 256
  hop_length: 1024
  min_mean_abs: 0.01
  n_fft: 8192
  num_channels: 2
  sample_rate: 44100
model:
  act: gelu
  bottleneck_factor: 4
  growth: 64
  norm: InstanceNorm
  num_blocks_per_scale: 2
  num_channels: 64
  num_scales: 5
  num_subbands: 4
  scale:
  - 2
  - 2
training:
  batch_size: 6
  coarse_loss_clip: false
  datasets:
  - ../data/moises/bleeding
  ema_momentum: 0.999
  grad_clip: null
  instruments:
  - Vocals
  - Drums
  - Bass
  - Other
  lr: 0.0001
  num_steps: 150000
  q: 0.93
  target_instrument: null
inference:
  batch_size: 2
  dim_t: 256
  num_overlap: 8